# : Manager [[[

[manager]
cwd = { fg = "#ede0d4" }

# Tab
tab_active = { fg = "#452b00", bg = "#f4bd6f", bold = true }
tab_inactive = { fg = "#ffddb3", bg = "#291800" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#a2d26e", bg = "#a2d26e" }
marker_cut = { fg = "#d4eabc", bg = "#d4eabc" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b8cea1", bg = "#b8cea1" }

# Count
count_copied = { fg = "#102004", bg = "#d4eabc" }
count_cut = { fg = "#102004", bg = "#d4eabc" }
count_selected = { fg = "#452b00", bg = "#b8cea1" }

# Border
border_symbol = "‚îÇ"
border_style  = { fg = "#f4bd6f" }

# : ]]]


# : Status [[[

[status]
separator_open = "ü≠Å"
separator_close = "ü≠†"
separator_style = { bg = "#452b00", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f4bd6f", fg = "#452b00", bold = true }
normal_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Select mode
select_main = { bg = "#ddc2a1", fg = "#3e2d16", bold = true }
select_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Unset mode
unset_main = { bg = "#b8cea1", fg = "#243515", bold = true }
unset_alt  = { bg = "#4f4539", fg = "#d3c4b4" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f4bd6f", bg = "#3f3830" }
progress_error = { fg = "#ffb4ab", bg = "#3f3830" }

# Permissions
permissions_t = { fg = "#a8783d" }
permissions_w = { fg = "#6c8d49" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#89c548" }
permissions_s = { fg = "#ff991a" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f4bd6f" }
active = { fg = "#b8cea1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f4bd6f" }
value = { fg = "#ede0d4" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f4bd6f", bg = "#452b00" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f4bd6f" }
title = {}
hovered = { fg = "#d4eabc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3f3830" }
cand = { fg = "#f4bd6f" }
rest = { fg = "#452b00" }
desc = { fg = "#ede0d4" }
separator = " ‚ñ∂ "
separator_style = { fg = "#ede0d4" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ede0d4" }
run = { fg = "#ede0d4" }
footer = { fg = "#3e2d16", bg = "#ddc2a1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b8cea1" }
title_warn = { fg = "#f4bd6f" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ede0d4" },
    { name = "*/", fg = "#f4bd6f" },
]

# : ]]]
