[opener]
pdff = [
	{ run = '(xournalpp "$@") ', desc = "xournalpp", orphan = true, for = "unix" },
	]
edit = [
	{ run = 'code "$@"', desc = "code", block = true, for = "unix" },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]


[open]
rules = [
	#PDF
	{mime = "application/pdf", use = [ "pdff", "reveal" ] },
    # Text
    { mime = "text/*", use = ["edit", "reveal"] },
    # Media
    { mime = "{audio,video}/*", use = ["play", "reveal"] },
]
